### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-anamontiaga#1]
Buen trabajo @anamontiaga !

Algunas pistas para acabarlo:

## React

- [x] Usa el `id` de cada pokemon para el `key` de react cuando mapeas y creas un listado de componentes
- [x] Mover `li` fuera del componente 'Pokemon', de esta manera es una tarjeta simple que podemos usar en cualquier lugar, no solo dentro de un 'ul` (opcional)
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser h3 sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.

## CSS

- [x] Agregar estilos (un archivo por componente)

## HTML

- [x] Revise los metadatos en index.html (lang, title ...)

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by anamontiaga** [comment]
Gracias por el feedback, Miguel.

Ya están incorporados los cambios.

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-4321a1fa-69b2-4398-996b-3bc48c4dc787-v1.png?transparent=1&palette=1&width=246)
